### PR TITLE
go: switch to go.mod, Mac build fixes

### PR DESCRIPTION
**Pull request by djs55**
Although the go code is tested by CI on Linux, the Mac CI is currently broken and doesn't pick up failures in Mac-specific parts.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like your git config doesn't match your sign-off; (DCO check can be picky with that)

```
Commit sha: ac55ea3, Author: David Scott, Committer: David Scott; Expected "David Scott dave@recoil.org", but got "David Scott dave.scott@docker.com".
```

**Comment by djs55** [comment]
@thaJeztah ah yes, I'd better fix that!

**Comment by thaJeztah** [comment]
I should mention that you _can_ manually mark it to "pass" if needed. Not sure if it supports a `.mailmap` file (which could work for this otherwise)

**Comment by simonferquel** [comment]
lgtm

**Comment by djs55** [comment]
OK I'm able to vendor this into another repo successfully 😅 ... the true test of `go.mod`

Regarding CI:
- travis: hit a Docker rate limit
- circleci: broken for an unrelated reason (fixed in a concurrent PR)
- appveyor: Windows is broken and can't be fixed until we get rid of the Cygwin dependency (currently blocked on using `opam monorepo` which is blocked on switching `uwt` for `luv` and updating the `tcpip` package version)
- DCO: pass!

**Pull request merged**
