### PR TITLE
make Kubernetes controller call libproxy directly instead of exec

### LINKED ISSUE #306: vpnkit-expose-port-controller could call the API directly instead of exec
We currently have some code that execs `vpnkit-expose-port` and stores pid files in state dir etc, we shouldn't need to do all that if we could call the Go API directly.

### PR DESCRIPTION
**Pull request by errordeveloper**
Close #306.

### CODE REVIEW

**Comment by errordeveloper** [comment]
@djs55 I've not tested this properly yet, so it's just WIP/FIY for now, and – no rush to review it.

**Comment by djs55** [comment]
I've force pushed a rebase to latest master which has a travis fix.

**Comment by errordeveloper** [comment]
@djs55 thanks! I've rebased this also.

**Comment by djs55** [comment]
Thanks!

**Pull request merged**
