### PR TITLE
Add Kubernetes port forwarder controller running inside the VM using the vpnkit.Client

### PR DESCRIPTION
**Pull request by guillaumerose**

### CODE REVIEW

**Comment by djs55** [comment]
I've force-pushed a rebase to master now that travis is fixed.

**Comment by djs55** [comment]
Restarted travis -- it seemed to fail with an I/O error installing packages.

**Comment by djs55** [comment]
Travis is green! Merging

**Comment by guillaumerose** [comment]
Thanks!

**Pull request merged**
