### PR TITLE
Fix dns dev version

### PR DESCRIPTION
**Pull request by samoht**
/cc @MagnusS 

Can you try to see if it works better for you?

### CODE REVIEW

**Comment by MagnusS** [comment]
Hm it didn't work with just an update and a new --deps-only install, it still installed conduit 1.0.0. I'm trying to build on a new root now, in case my testing left it in a weird state - but takes a short while as it has to build ocaml 4.04.2 after the homebrew update

**Comment by samoht** [comment]
Not sure if it is worth spending too much time on this anyway ... hopefully things will become easier once #262 is merged

**Comment by MagnusS** [comment]
This patch + update upstream deps with `make` in `/repo` fixed it for me. I now have `conduit 0.14.5` and build instructions work again

**Comment by MagnusS** [comment]
I also had to run `opam switch 4.04.2` first

**Comment by samoht** [comment]
@MagnusS: `make OSS-LICENSE` is now failing

**Comment by MagnusS** [comment]
Ok, as discussed on slack I'll try to just add the constraint to mirage-conduit manually instead of doing a full update to avoid conflicts with #262.

**Comment by samoht** [comment]
The mirage3 branch has been merged, so I'm closing this PR.

**Pull request closed without merging**
