### PR TITLE
travis: update to docker 17.05 for multistage build

### PR DESCRIPTION
**Pull request by MagnusS**
Try to upgrade Docker to 17.05 to see if we can use the multi-stage build instead of maintaining two sets of Dockerfiles.

### CODE REVIEW

**Comment by MagnusS** [comment]
Looks like it works! Should I remove the other Dockerfiles in this PR as well?

**Comment by djs55** [comment]
Let's simplify and delete as much as possible-- do we need the other Dockerfiles? I guess we already have `Makefile` targets for building the binaries if you want to do that separately.

**Comment by MagnusS** [comment]
I don't think so, I guess Docker cloud is using the multistage build as well - so removing

**Comment by MagnusS** [comment]
All green! But looks like I've lost merge access here

**Comment by djs55** [comment]
I’ve sent you an invite link. If you accept it I think you should get merge access.

**Comment by MagnusS** [comment]
@djs55 thanks!

**Pull request merged**
